name: flutter_colorpicker
description: A HSV(HSB)/HSL color picker inspired by chrome devtools and a material color picker for your flutter app.
version: 0.6.0
homepage: https://github.com/mchome/flutter_colorpicker

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
