name: flutter_colorpicker
description: A HSV color picker for your flutter app.
version: 0.0.6
author: "fuyumi <fnatic.roach@gmail.com>"
homepage: https://github.com/mchome/flutter_colorpicker

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"